from pathlib import Path

from jinja2 import Environment, FileSystemLoader


def get_project_root() -> Path:
    """
    Return the main project folder.

    Example:
    C:/Users/sahil jc/caseforge
    """
    return Path(__file__).resolve().parent.parent


def render_template(template_name: str, data: dict) -> str:
    """
    Take a template file and fill it with data.

    Template:
    MACH_NUMBER = {{ mach_number }}

    Data:
    mach_number = 0.3

    Final output:
    MACH_NUMBER = 0.3
    """
    package_dir = Path(__file__).resolve().parent
    templates_dir = package_dir / "templates"

    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        trim_blocks=True,
        lstrip_blocks=True,
    )

    template = env.get_template(template_name)
    return template.render(**data)

def write_text_file(file_path: Path, content: str) -> None:
    """
    Create parent folders if needed and write text into a file.
    """
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(content, encoding="utf-8")


def create_nozzle_case(
    output_dir: str,
    mesh_file: str,
    inlet_pressure: float,
    outlet_pressure: float,
    temperature: float,
    iterations: int,
) -> list[Path]:
    """
    Create a starter SU2 Euler nozzle case.

    This creates:
    - case.cfg
    - run.bat
    - run.sh
    - case_info.md
    """
    output_path = Path(output_dir)

    data = {
        "mesh_file": mesh_file,
        "inlet_pressure": inlet_pressure,
        "outlet_pressure": outlet_pressure,
        "temperature": temperature,
        "iterations": iterations,
        "gamma": 1.4,
        "gas_constant": 296.8,
        "cfl": 1.0,
    }

    cfg_text = render_template("nozzle_euler.cfg.j2", data)

    run_bat_text = "SU2_CFD case.cfg\n"

    run_sh_text = """#!/usr/bin/env bash
SU2_CFD case.cfg
"""

    case_info_text = f"""# CaseForge Nozzle Case

This case was generated by CaseForge.

## Case Type

Internal cold-gas nozzle, inviscid Euler starter case.

## Inputs

| Parameter | Value |
|---|---:|
| Mesh file | {mesh_file} |
| Inlet total pressure | {inlet_pressure} Pa |
| Outlet static pressure | {outlet_pressure} Pa |
| Temperature | {temperature} K |
| Iterations | {iterations} |
| Gas constant | 296.8 J/kg/K |
| Gamma | 1.4 |

## Expected Mesh Boundary Names

Your SU2 mesh should contain these marker names:

- inlet
- outlet
- wall
- symmetry

If your mesh uses different boundary names, edit case.cfg so the names match your mesh.

## How to Run

On Windows:

run.bat

Or directly:

SU2_CFD case.cfg

## Notes

This is a starter configuration. You should verify boundary names, mesh quality, and solver settings for your exact nozzle geometry.
"""
    files_to_write = {
        output_path / "case.cfg": cfg_text,
        output_path / "run.bat": run_bat_text,
        output_path / "run.sh": run_sh_text,
        output_path / "case_info.md": case_info_text,
    }

    for file_path, content in files_to_write.items():
        write_text_file(file_path, content)

    return list(files_to_write.keys())
def create_generic_case(
    output_dir: str,
    mesh_file: str,
    solver: str,
    iterations: int,
    cfl: float,
    wall_marker: str,
    farfield_marker: str,
    freestream_pressure: float,
    freestream_temperature: float,
) -> list[Path]:
    """
    Create a generic editable SU2 starter case.

    This creates:
    - case.cfg
    - run.bat
    - run.sh
    - case_info.md
    """
    output_path = Path(output_dir)

    data = {
        "mesh_file": mesh_file,
        "solver": solver,
        "iterations": iterations,
        "cfl": cfl,
        "wall_marker": wall_marker,
        "farfield_marker": farfield_marker,
        "freestream_pressure": freestream_pressure,
        "freestream_temperature": freestream_temperature,
    }

    cfg_text = render_template("generic.cfg.j2", data)

    run_bat_text = "SU2_CFD case.cfg\n"

    run_sh_text = """#!/usr/bin/env bash
SU2_CFD case.cfg
"""

    case_info_text = f"""# CaseForge Generic SU2 Case

This case was generated by CaseForge.

## Case Type

Generic editable SU2 starter case.

## Inputs

| Parameter | Value |
|---|---:|
| Solver | {solver} |
| Mesh file | {mesh_file} |
| Iterations | {iterations} |
| CFL number | {cfl} |
| Wall marker | {wall_marker} |
| Farfield marker | {farfield_marker} |
| Freestream pressure | {freestream_pressure} Pa |
| Freestream temperature | {freestream_temperature} K |

## Important Note

This is a generic starter config.

You must edit boundary conditions and physical settings based on your actual CFD case.

## How to Run

On Windows:

run.bat

Or directly:

SU2_CFD case.cfg
"""

    files_to_write = {
        output_path / "case.cfg": cfg_text,
        output_path / "run.bat": run_bat_text,
        output_path / "run.sh": run_sh_text,
        output_path / "case_info.md": case_info_text,
    }

    for file_path, content in files_to_write.items():
        write_text_file(file_path, content)

    return list(files_to_write.keys())